### ISSUE TITLE
Quick Paleographer

### ISSUE THREAD

**Issue by Jegb1972** [wujastyk/sushrutaproject#13]
BTW, Dominik, I had to stop using the quick palaeographer. It became too difficult to navigate around the image of a folio. The image kept 'jumping' when I moved. I thought it might be the poor quality of my internet in quarantine, but I've had the same problem since moving to a place in Sydney. 

Also, the image in quick palaeographer was significantly more pixelated than viewing it on my laptop using a pdf reader. 

So, I am compiling screen shots of akṣaras in a separate document. The output is not as pretty as that of the quick palaeographer, but it is facilitating my learning of the script and provide a useful record. I asked Andrey whether he had made such a table. He used B 0029-19 as his point of reference rather than recording unique akṣaras of KL699's orthography. However, I think such a record might be worth including in the introduction to a critical edition, seeing that KL699 is so old and the main witness, which makes the peculiarities of its orthography important for readers of the edition and scholars of Nepalese manuscripts more generally.

Best wishes,

Jason

**Comment by wujastyk** [comment]
- It is worth writing to Charles about problems with quick palaeographer (QP), since he is quick to fix problems.  Even better, perhaps, is to report the difficulties as "issues" in QP's [Github repo](https://github.com/chchch/quick-palaeographer/).
- I do not have either of the problems you report, which is odd.
- Finally, it's extremely easy to download the QP software from its home on Github and run it on your own computer.  No installation required, just the download.  That would eliminate any internet-related problems.  But what you describe doesn't sound like an interned problem.

**Comment by Jegb1972** [comment]
Yes, I was using the QP in my browser (Apple's Safari). That could have been the problem.

**Comment by wujastyk** [comment]
it is a browser-based system, so even if you download the code, you'll
still be using your browser.
